name: Check File Changes

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for changes in file
      run: |
        git fetch
        echo "CHANGED_FILES=$(git diff origin/main --name-only)" >> $GITHUB_ENV
    - name: Print Env
      run: echo $CHANGED_FILES
