name: Check File Changes

on:
  pull_request:
    branches:
      - main
      - staging
      - release

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in file
        run: |
          git fetch
          ALL_CHANGES= "$(git ls-tree -r origin/main --name-only src/main/resources/db/migration)"
          echo "$ALL_CHANGES"
          FILES_INDIR="$(ls -a src/main/resources/db/migration)"
          echo "$FILES_INDIR"
          
