name: Check File Changes

on:
  pull_request:
    branches:
      - main
      - staging
      - release

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in file
        run: |
          git fetch
          ALL_CHANGES="$(diff -rq origin/main/src/resources/db/migrations /src/resources/db/migrations)"
          echo "$ALL_CHANGES"
          
