name: Check File Changes

on:
  pull_request:
    branches:
      - main
      - staging
      - release

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in file
        run: |
          git fetch
          FILES_IN_BRANCH="$(git ls-tree -r origin/main --name-only src/main/resources/db/migration)"
          echo "$FILES_IN_BRANCH"
          echo "FILES IN LOCAL"
          FILES_INDIR="$(ls src/main/resources/db/migration)"
          echo "$FILES_IN_DIR"
          FILE_COUNT_IN_BRANCH="$(echo -n "$FILES_IN_BRANCH" | wc -l)"
          FILE_COUNT_IN_DIR="$(echo -n "$FILES_IN_DIR" | wc -l)"
          echo $FILE_COUNT_IN_BRANCH
          echo $FILE_COUNT_IN_DIR
