name: Check File Changes

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for changes in file
      run: |
        CHANGED_FILES="$(git diff HEAD --name-only)"
        if echo "$CHANGED_FILES" | grep -q .env.sample; then
          echo "File has changed"
          exit 0
        else
          echo "File has not changed"
          exit 1
        fi
