name: Check File Changes

on:
  pull_request:
    branches:
      - main
      - staging
      - release

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in file
        run: |
          git fetch
          EVENT_DATA=$(cat $GITHUB_EVENT_PATH)
          TARGET_BRANCH_NAME=$(echo $EVENT_DATA | jq .pull_request.base.ref | tr -d '"')
          echo $TARGET_BRANCH_NAME
          DIFFRENCE_DIRECTORY="$(git diff --name-only "origin/$TARGET_BRANCH_NAME":src/main/resources/db/migration src/main/resources/db/migration)"
          echo "$DIFFRENCE_DIRECTORY"
          FILES_IN_TARGET_BRANCH="$(git ls-tree -r "origin/$TARGET_BRANCH_NAME" --name-only src/main/resources/db/migration)"
          echo "$FILES_IN_TARGET_BRANCH"
          echo "FILES IN LOCAL"
          FILES_IN_DIR="$(ls src/main/resources/db/migration)"
          echo "$FILES_IN_DIR"
          TIME_STAMP_IN_BRANCH=($(echo "$FILES_IN_TARGET_BRANCH" | grep -oE 'v[0-9]+' | cut -c2-))
          TIME_STAMP_IN_DIFFRENCE=($(echo "$DIFFRENCE_DIRECTORY" | grep -oE 'v[0-9]+' | cut -c2-))
          echo "${TIME_STAMP_IN_BRANCH[@]}"
          echo "${TIME_STAMP_IN_DIFFRENCE[@]}"
          TIME_STAMP_IN_BRANCH_LAST=${TIME_STAMP_IN_BRANCH[-1]}
          PULL_REQUEST_NUMBER=$(echo $EVENT_DATA | jq .pull_request.number)
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}/reviews"
          for val in "${TIME_STAMP_IN_DIFFRENCE[@]}"; do
            
            if [[ "$val" -lt "$TIME_STAMP_IN_BRANCH_LAST" ]]; then
              BODY="Stale Time Stamp migrations"
              curl -H "Authorization: token ${{secrets.TOKEN_SECRET}}" -X POST -d "{\"body\":\"$BODY\",\"event\":\"COMMENT\"}" $API_URL
              exit 1
            fi
          done

