name: Check File Changes

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for changes in file
      run: |
        git fetch
        CHANGED_FILES="$(git diff origin/main --name-only)"
        echo "$CHANGED_FILES"
        if echo "$CHANGED_FILES" | grep -q .env.sample; then
          echo "File has changed"
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "File has not changed"
          echo "CHANGED=false" >> $GITHUB_ENV
        fi
    - name: Print Output
      run: echo $CHANGED
    - name: Check wether changes in file or not  
      if: ${{ env.CHANGED == true }}
      run: echo "File Changed"
